import { describe, expect, it } from "vitest";
import { contactsToCsv } from "@/lib/contacts/csv";
import { isAllowedDuplicateReviewAction, parseAdminListParams } from "@/lib/contacts/admin";

describe("contact CSV export", () => {
  it("escapes quotes, commas, and line breaks", () => { const csv = contactsToCsv([{ record_id: "ICFT-C-000001", first_name: "Ada, \"A\"\nLovelace", status: "new" }]); expect(csv).toContain('"Ada, ""A"" Lovelace"'); });
  it("prevents spreadsheet formula interpretation", () => { const csv = contactsToCsv([{ record_id: "=SUM(1,1)", first_name: "+formula", status: "new" }]); expect(csv).toContain('"\'=SUM(1,1)"'); expect(csv).toContain('"\'+formula"'); });
  it("uses the complete readable Contact-only column set", () => { const csv = contactsToCsv([]); expect(csv.slice(1).split("\r\n")[0]).toBe("Record ID,First Name,Last Name,Preferred Name,Email Address,Roles,Other Role,Organization / Institution,Position / Professional Title,Country / Region,Broad Research / Professional Interest,Detailed Research / Professional Interest,Permission to Receive Conference Updates,Consent Timestamp,Contact Status,Duplicate Status,Submission Source,Admin Notes,Created At,Updated At,Archived At"); });
  it("maps every stored Contact export field to its intended column", () => { const csv = contactsToCsv([{ record_id: "ICFT-C-000001", first_name: "Ada", last_name: "Lovelace", preferred_name: null, email: "ada@example.com", roles: ["Researcher", "Speaker"], other_role: null, organization: "ICFT", professional_title: "Researcher", country_region: "CA", general_field: "Forestry", specific_research_area: "Forest health", conference_updates_consent: false, consent_timestamp: "2026-08-01T00:00:00.000Z", status: "new", duplicate_status: "no_duplicate_detected", submission_source: "qr_code", admin_notes: "Reviewed", created_at: "2026-08-01T01:00:00.000Z", updated_at: "2026-08-02T01:00:00.000Z", archived_at: null }]); expect(csv.split("\r\n")[1]).toBe('"ICFT-C-000001","Ada","Lovelace","","ada@example.com","Researcher; Speaker","","ICFT","Researcher","CA","Forestry","Forest health","false","2026-08-01T00:00:00.000Z","new","no_duplicate_detected","qr_code","Reviewed","2026-08-01T01:00:00.000Z","2026-08-02T01:00:00.000Z",""'); });
  it("never mixes Research Prospect-only fields into a Contact export", () => { const csv = contactsToCsv([{ record_id: "ICFT-C-000001", first_name: "Ada", last_name: "Lovelace", status: "new", priority: "PROSPECT_PRIORITY_MARKER", review_status: "PROSPECT_REVIEW_MARKER", identity_verified: "PROSPECT_VERIFICATION_MARKER", discovery_batch: "PROSPECT_BATCH_MARKER" }]); expect(csv).not.toMatch(/PROSPECT_(?:PRIORITY|REVIEW|VERIFICATION|BATCH)_MARKER/u); expect(csv).not.toMatch(/Priority|Review Status|Identity Verified|Discovery Batch/u); });
  it("preserves roles, consent booleans, Unicode, emails, and URLs", () => { const csv = contactsToCsv([{ record_id: "ICFT-C-000001", first_name: "王", last_name: "小明", email: "name@example.com", roles: ["Researcher", "Other"], other_role: "https://example.com/profile", conference_updates_consent: false, status: "new" }, { record_id: "ICFT-C-000002", first_name: "Élodie", last_name: "Durand", email: "elodie@example.com", roles: ["Researcher"], conference_updates_consent: true, status: "new" }]); expect(csv).toContain('"Researcher; Other"'); expect(csv).toContain('"false"'); expect(csv).toContain('"true"'); expect(csv).toContain('"王"'); expect(csv).toContain('"name@example.com"'); expect(csv).toContain('"https://example.com/profile"'); });
  it("neutralizes every formula prefix after spreadsheet whitespace", () => { const csv = contactsToCsv([{ record_id: "ICFT-C-000001", first_name: " \t=HYPERLINK(\"https://evil.test\")", last_name: "+cmd", preferred_name: "-cmd", organization: "@cmd", status: "new" }]); expect(csv).toContain('"\' \t=HYPERLINK(""https://evil.test"")"'); expect(csv).toContain('"\'+cmd"'); expect(csv).toContain('"\'-cmd"'); expect(csv).toContain('"\'@cmd"'); });
  it("preserves duplicate filter state and allows only review actions", () => { expect(parseAdminListParams({ duplicate: "possible_duplicate" }).duplicate).toBe("possible_duplicate"); expect(isAllowedDuplicateReviewAction("reviewed")).toBe(true); expect(isAllowedDuplicateReviewAction("keep_separate")).toBe(true); expect(isAllowedDuplicateReviewAction("merged")).toBe(false); });
});
