import { countryRegionValues } from "@/lib/contacts/options";
import { prospectPriorities, prospectReviewStatuses, type ProspectPriority, type ProspectReviewStatus } from "./options";

const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/u;
const priorities = new Set<string>(prospectPriorities); const statuses = new Set<string>(prospectReviewStatuses);
export type ProspectInput = { first_name: string; last_name: string; preferred_name: string | null; organization: string | null; department: string | null; position_title: string | null; country_region: string | null; public_email: string | null; relevance_reason: string | null; priority: ProspectPriority; review_status: ProspectReviewStatus; notes: string | null; identity_verified: boolean; affiliation_verified: boolean; relevance_verified: boolean; email_verified: boolean; last_verified_at: string | null; discovery_batch: string | null; };
function value(form: FormData, name: string, max: number, required = false) { const raw = form.get(name); const text = typeof raw === "string" ? raw.trim() : ""; if ((required && !text) || text.length > max) return null; return text || null; }
export function validateProspect(form: FormData): { success: true; data: ProspectInput } | { success: false } {
  const first_name = value(form, "firstName", 100, true); const last_name = value(form, "lastName", 100, true); const public_email = value(form, "publicEmail", 254)?.toLowerCase() ?? null;
  const country_region = value(form, "countryRegion", 2); const priority = value(form, "priority", 2, true); const review_status = value(form, "reviewStatus", 20, true); const date = value(form, "lastVerifiedAt", 30);
  if (!first_name || !last_name || (public_email && !emailPattern.test(public_email)) || (country_region && !countryRegionValues.has(country_region)) || !priority || !priorities.has(priority) || !review_status || !statuses.has(review_status) || (date && Number.isNaN(Date.parse(date)))) return { success: false };
  return { success: true, data: { first_name, last_name, preferred_name: value(form, "preferredName", 100), organization: value(form, "organization", 200), department: value(form, "department", 200), position_title: value(form, "positionTitle", 200), country_region, public_email, relevance_reason: value(form, "relevanceReason", 5000), priority: priority as ProspectPriority, review_status: review_status as ProspectReviewStatus, notes: value(form, "notes", 5000), identity_verified: form.get("identityVerified") === "on", affiliation_verified: form.get("affiliationVerified") === "on", relevance_verified: form.get("relevanceVerified") === "on", email_verified: form.get("emailVerified") === "on", last_verified_at: date ? new Date(date).toISOString() : null, discovery_batch: value(form, "discoveryBatch", 200) } };
}
export function parseProspectListParams(params: Record<string, string | string[] | undefined>) { const get = (name: string) => typeof params[name] === "string" ? params[name].trim() : ""; const page = Number.parseInt(get("page"), 10); const priority = get("priority"); const status = get("status"); const country = get("country"); const emailVerified = get("emailVerified"); return { query: get("q").slice(0, 100), priority: priorities.has(priority) ? priority : "", status: statuses.has(status) ? status : "", country: countryRegionValues.has(country) ? country : "", emailVerified: emailVerified === "yes" || emailVerified === "no" ? emailVerified : "", page: Number.isFinite(page) && page > 0 ? page : 1 }; }
