import "server-only";
import { createClient } from "@/lib/supabase/server";
import { parseProspectListParams } from "./admin";
import { filterProspectExportRows, type ProspectExportRow } from "./export";
const listColumns = "id,first_name,last_name,preferred_name,organization,country_region,position_title,public_email,priority,review_status,identity_verified,affiliation_verified,relevance_verified,email_verified,last_verified_at,created_at";
const detailColumns = "id,first_name,last_name,preferred_name,organization,department,position_title,country_region,public_email,relevance_reason,priority,review_status,notes,identity_verified,affiliation_verified,relevance_verified,email_verified,last_verified_at,discovery_batch,discovered_at,created_at,updated_at";
function escape(value: string) { return value.replace(/[,%()]/g, ""); }
function applyProspectFilters<T extends { eq: (column: string, value: string | boolean) => T; or: (filters: string) => T }>(query: T, filters: ReturnType<typeof parseProspectListParams>) { if (filters.priority) query = query.eq("priority", filters.priority); if (filters.status) query = query.eq("review_status", filters.status); if (filters.country) query = query.eq("country_region", filters.country); if (filters.emailVerified) query = query.eq("email_verified", filters.emailVerified === "yes"); if (filters.discoveryBatch) query = query.eq("discovery_batch", filters.discoveryBatch); if (filters.query) { const q = escape(filters.query); query = query.or(`first_name.ilike.%${q}%,last_name.ilike.%${q}%,preferred_name.ilike.%${q}%,organization.ilike.%${q}%,public_email.ilike.%${q}%`); } return query; }
export async function getProspects(params: Record<string, string | string[] | undefined>) { const filters = parseProspectListParams(params); const supabase = await createClient(); const query = applyProspectFilters(supabase.from("research_prospects").select(listColumns, { count: "exact" }).order("created_at", { ascending: false }).order("id", { ascending: false }).range((filters.page - 1) * 25, filters.page * 25 - 1), filters); const { data, count, error } = await query; return { prospects: data ?? [], total: count ?? 0, filters, error: Boolean(error) }; }
const exportColumns = "first_name,last_name,preferred_name,organization,position_title,country_region,public_email,priority,review_status,identity_verified,affiliation_verified,relevance_verified,email_verified,discovery_batch,last_verified_at,created_at,updated_at,research_prospect_tag_assignments(research_tags(name)),research_prospect_flags(flag),research_prospect_sources(source_url,source_type,source_title)";
type ProspectExportDatabaseRow = Omit<ProspectExportRow, "tags" | "flags" | "sources"> & { research_prospect_tag_assignments: { research_tags: { name: string } | { name: string }[] | null }[] | null; research_prospect_flags: { flag: string }[] | null; research_prospect_sources: ProspectExportRow["sources"] | null; };
function tagNames(assignments: ProspectExportDatabaseRow["research_prospect_tag_assignments"]) { return (assignments ?? []).flatMap(({ research_tags }) => Array.isArray(research_tags) ? research_tags.map(tag => tag.name) : research_tags?.name ? [research_tags.name] : []); }
export async function getProspectsForExport(params: Record<string, string | string[] | undefined>) { const filters = filterProspectExportRows(params); const supabase = await createClient(); const rows: ProspectExportRow[] = []; for (let from = 0; ; from += 1000) { const query = applyProspectFilters(supabase.from("research_prospects").select(exportColumns).order("created_at", { ascending: false }).order("id", { ascending: false }).range(from, from + 999), filters); const { data, error } = await query; if (error) return { rows: [], error: true }; const batch = (data ?? []) as unknown as ProspectExportDatabaseRow[]; rows.push(...batch.map(row => ({ ...row, tags: tagNames(row.research_prospect_tag_assignments), flags: (row.research_prospect_flags ?? []).flatMap(flag => flag.flag ? [flag.flag] : []), sources: row.research_prospect_sources ?? [] }))); if (batch.length < 1000) break; } return { rows, error: false }; }
export async function getProspect(id: string) { const supabase = await createClient(); const [{ data: prospect }, { data: sources }, { data: assignments }, { data: flags }] = await Promise.all([supabase.from("research_prospects").select(detailColumns).eq("id", id).maybeSingle(), supabase.from("research_prospect_sources").select("id,source_url,source_type,source_title,supports,accessed_at,created_at").eq("research_prospect_id", id).order("created_at"), supabase.from("research_prospect_tag_assignments").select("research_tag_id,research_tags(id,name)").eq("research_prospect_id", id), supabase.from("research_prospect_flags").select("id,flag").eq("research_prospect_id", id).order("flag")]); return { prospect, sources: sources ?? [], tags: assignments ?? [], flags: flags ?? [] }; }
export async function findPossibleDuplicates(id: string, email: string | null, firstName: string, lastName: string, organization: string | null) { const supabase = await createClient(); if (email) { const { data } = await supabase.from("research_prospects").select("id,first_name,last_name,organization,public_email").eq("public_email", email).neq("id", id); return data ?? []; } if (!organization) return []; const { data } = await supabase.from("research_prospects").select("id,first_name,last_name,organization,public_email").ilike("first_name", firstName).ilike("last_name", lastName).ilike("organization", organization).neq("id", id); return data ?? []; }
