import "server-only";
import { createClient } from "@/lib/supabase/server";
import { parseProspectListParams } from "./admin";
const listColumns = "id,first_name,last_name,preferred_name,organization,country_region,position_title,public_email,priority,review_status,identity_verified,affiliation_verified,relevance_verified,email_verified,last_verified_at,created_at";
const detailColumns = "id,first_name,last_name,preferred_name,organization,department,position_title,country_region,public_email,relevance_reason,priority,review_status,notes,identity_verified,affiliation_verified,relevance_verified,email_verified,last_verified_at,discovery_batch,discovered_at,created_at,updated_at";
function escape(value: string) { return value.replace(/[,%()]/g, ""); }
export async function getProspects(params: Record<string, string | string[] | undefined>) { const filters = parseProspectListParams(params); const supabase = await createClient(); let query = supabase.from("research_prospects").select(listColumns, { count: "exact" }).order("created_at", { ascending: false }).range((filters.page - 1) * 25, filters.page * 25 - 1); if (filters.priority) query = query.eq("priority", filters.priority); if (filters.status) query = query.eq("review_status", filters.status); if (filters.country) query = query.eq("country_region", filters.country); if (filters.emailVerified) query = query.eq("email_verified", filters.emailVerified === "yes"); if (filters.query) { const q = escape(filters.query); query = query.or(`first_name.ilike.%${q}%,last_name.ilike.%${q}%,preferred_name.ilike.%${q}%,organization.ilike.%${q}%,public_email.ilike.%${q}%`); } const { data, count, error } = await query; return { prospects: data ?? [], total: count ?? 0, filters, error: Boolean(error) }; }
export async function getProspect(id: string) { const supabase = await createClient(); const [{ data: prospect }, { data: sources }, { data: assignments }, { data: flags }] = await Promise.all([supabase.from("research_prospects").select(detailColumns).eq("id", id).maybeSingle(), supabase.from("research_prospect_sources").select("id,source_url,source_type,source_title,supports,accessed_at,created_at").eq("research_prospect_id", id).order("created_at"), supabase.from("research_prospect_tag_assignments").select("research_tag_id,research_tags(id,name)").eq("research_prospect_id", id), supabase.from("research_prospect_flags").select("id,flag").eq("research_prospect_id", id).order("flag")]); return { prospect, sources: sources ?? [], tags: assignments ?? [], flags: flags ?? [] }; }
export async function findPossibleDuplicates(id: string, email: string | null, firstName: string, lastName: string, organization: string | null) { const supabase = await createClient(); if (email) { const { data } = await supabase.from("research_prospects").select("id,first_name,last_name,organization,public_email").eq("public_email", email).neq("id", id); return data ?? []; } if (!organization) return []; const { data } = await supabase.from("research_prospects").select("id,first_name,last_name,organization,public_email").ilike("first_name", firstName).ilike("last_name", lastName).ilike("organization", organization).neq("id", id); return data ?? []; }
