import Link from "next/link";
import { notFound } from "next/navigation";
import { requireApprovedAdmin } from "@/lib/auth/admin";
import { getDuplicateGroup } from "@/lib/contacts/admin-data";
import { setDuplicateReviewState } from "../../contacts/actions";
import styles from "../../admin.module.css";

function date(value: string | null) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }
export default async function DuplicateReviewPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ saved?: string }> }) { await requireApprovedAdmin(); const { id } = await params; const { contact, matches } = await getDuplicateGroup(id); if (!contact) notFound(); const query = await searchParams; return <main className={styles.page}><header className={styles.header}><div><Link href={`/admin/contacts/${id}`}>← Contact detail</Link><h1>Duplicate review</h1><p>Matching normalized email: {contact.email}</p></div><form action="/admin/logout" method="post"><button>Sign out</button></form></header>{query.saved && <p className={styles.notice} role="status">Duplicate review state saved.</p>}<p className={styles.summary}>{matches.length} matching records, including archived contacts.</p><div className={styles.comparison}>{matches.map((match) => <article className={styles.compareCard} key={match.id}><h2><Link href={`/admin/contacts/${match.id}`}>{match.record_id}</Link></h2><p><strong>{match.first_name} {match.last_name}</strong>{match.preferred_name ? ` (${match.preferred_name})` : ""}</p><dl><dt>Roles</dt><dd>{match.roles.join(", ")}{match.other_role ? ` — ${match.other_role}` : ""}</dd><dt>Organization</dt><dd>{match.organization ?? "—"}</dd><dt>Title</dt><dd>{match.professional_title ?? "—"}</dd><dt>Country</dt><dd>{match.country_region}</dd><dt>Status</dt><dd>{match.status.replaceAll("_", " ")}</dd><dt>Duplicate state</dt><dd>{match.duplicate_status.replaceAll("_", " ")}</dd><dt>Archived</dt><dd>{date(match.archived_at)}</dd><dt>Created</dt><dd>{date(match.created_at)}</dd></dl><div className={styles.mutations}><form action={setDuplicateReviewState.bind(null, match.id, "reviewed")}><button>Mark Reviewed</button></form><form action={setDuplicateReviewState.bind(null, match.id, "keep_separate")}><button>Keep Separate</button></form></div></article>)}</div></main>; }
