import Link from "next/link";
import { notFound } from "next/navigation";
import type { ReactNode } from "react";
import { ArchiveButton } from "@/components/admin/archive-button";
import { requireApprovedAdmin } from "@/lib/auth/admin";
import { contactStatuses } from "@/lib/contacts/admin";
import { getAdminContact } from "@/lib/contacts/admin-data";
import { countryRegionOptions, roleOptions } from "@/lib/contacts/options";
import { setContactArchived, updateContact } from "../actions";
import styles from "../../admin.module.css";

function date(value: string | null) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }
function Meta({ label, value }: { label: string; value: ReactNode }) { return <div><dt>{label}</dt><dd>{value || "—"}</dd></div>; }
export default async function ContactDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ saved?: string; error?: string }> }) {
  await requireApprovedAdmin(); const { id } = await params; const { contact } = await getAdminContact(id); if (!contact) notFound(); const query = await searchParams;
  const update = updateContact.bind(null, id); const archive = setContactArchived.bind(null, id, !contact.archived_at);
  return <main className={styles.page}><header className={styles.header}><div><Link href="/admin">← Contact dashboard</Link><h1>{contact.record_id}</h1><p>{contact.first_name} {contact.last_name}</p></div><form action="/admin/logout" method="post"><button>Sign out</button></form></header>
  {query.saved && <p className={styles.notice} role="status">Contact saved.</p>}{query.error && <p className={styles.error} role="alert">The contact could not be saved. Review the fields and try again.</p>}
  <section className={styles.detail}><div className={styles.meta}><Meta label="Record ID" value={contact.record_id}/><Meta label="Duplicate status" value={<span className={`${styles.badge} ${contact.duplicate_status === "possible_duplicate" ? styles.duplicate : ""}`}>{contact.duplicate_status.replaceAll("_", " ")}</span>}/><Meta label="Submission source" value={contact.submission_source}/><Meta label="Consent timestamp" value={date(contact.consent_timestamp)}/><Meta label="Created" value={date(contact.created_at)}/><Meta label="Last updated" value={date(contact.updated_at)}/><Meta label="Archived" value={date(contact.archived_at)}/></div>
  <form action={update} className={styles.form}><label>First name<input name="firstName" defaultValue={contact.first_name} required maxLength={100}/></label><label>Last name<input name="lastName" defaultValue={contact.last_name} required maxLength={100}/></label><label>Preferred name<input name="preferredName" defaultValue={contact.preferred_name ?? ""} maxLength={100}/></label><label>Email<input name="email" type="email" defaultValue={contact.email} required maxLength={254}/></label><fieldset><legend>Roles</legend><div className={styles.choices}>{roleOptions.map((role) => <label key={role}><input type="checkbox" name="roles" value={role} defaultChecked={contact.roles.includes(role)}/>{role}</label>)}</div></fieldset><label>Other role<input name="otherRole" defaultValue={contact.other_role ?? ""} maxLength={150}/></label><label>Organization<input name="organization" defaultValue={contact.organization ?? ""} maxLength={200}/></label><label>Professional title<input name="professionalTitle" defaultValue={contact.professional_title ?? ""} maxLength={200}/></label><label>Country / Region<select name="countryRegion" defaultValue={contact.country_region}>{countryRegionOptions.map((country) => <option key={country.value} value={country.value}>{country.label}</option>)}</select></label><label>General field<input name="generalField" defaultValue={contact.general_field ?? ""} maxLength={200}/></label><label>Status<select name="status" defaultValue={contact.status}>{contactStatuses.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select></label><fieldset><legend>Conference updates consent</legend><div className={styles.choices}><label><input type="radio" name="conferenceUpdatesConsent" value="yes" defaultChecked={contact.conference_updates_consent}/>Yes</label><label><input type="radio" name="conferenceUpdatesConsent" value="no" defaultChecked={!contact.conference_updates_consent}/>No</label></div></fieldset><label className={styles.full}>Specific research area<textarea name="specificResearchArea" defaultValue={contact.specific_research_area ?? ""} maxLength={2000}/></label><label className={styles.full}>Administrative notes<textarea name="adminNotes" defaultValue={contact.admin_notes ?? ""} maxLength={5000}/></label><div className={`${styles.mutations} ${styles.full}`}><button type="submit">Save changes</button></div></form>
  <form action={archive} className={styles.mutations}><ArchiveButton archived={Boolean(contact.archived_at)}/></form></section></main>;
}
