import Link from "next/link";
import { requireApprovedAdmin } from "@/lib/auth/admin";
import { contactStatuses, duplicateStatuses } from "@/lib/contacts/admin";
import { countryRegionOptions, roleOptions } from "@/lib/contacts/options";
import { getAdminContacts } from "@/lib/contacts/admin-data";
import styles from "./admin.module.css";

type Params = Record<string, string | string[] | undefined>;
function href(filters: Record<string, string | number>, page: number) { const params = new URLSearchParams(); Object.entries({ ...filters, page }).forEach(([key, value]) => { if (value && String(value) !== "active") params.set(key, String(value)); }); return `/admin?${params}`; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
export default async function AdminPage({ searchParams }: { searchParams: Promise<Params> }) {
  await requireApprovedAdmin(); const params = await searchParams; const { contacts, total, filters, error } = await getAdminContacts(params); const pages = Math.max(1, Math.ceil(total / 25));
  const filterValues = { q: filters.query, status: filters.status, duplicate: filters.duplicate, country: filters.country, role: filters.role, archived: filters.archived };
  return <main className={styles.page}><header className={styles.header}><div><h1>Contact dashboard</h1><p>Secure ICFT contact management.</p><p><Link href="/admin/prospects">Research Prospects</Link> · <Link href="/admin/settings/content">Edit public site content</Link></p></div><form action="/admin/logout" method="post"><button>Sign out</button></form></header>
    <form className={styles.filters}><label>Search<input name="q" defaultValue={filters.query} placeholder="Name, email, record ID…" /></label><label>Status<select name="status" defaultValue={filters.status}><option value="">All statuses</option>{contactStatuses.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select></label><label>Duplicate review<select name="duplicate" defaultValue={filters.duplicate}><option value="">All duplicate states</option>{duplicateStatuses.map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select></label><label>Country / Region<select name="country" defaultValue={filters.country}><option value="">All countries</option>{countryRegionOptions.map((country) => <option key={country.value} value={country.value}>{country.label}</option>)}</select></label><label>Role<select name="role" defaultValue={filters.role}><option value="">All roles</option>{roleOptions.map((role) => <option key={role}>{role}</option>)}</select></label><label>Records<select name="archived" defaultValue={filters.archived}><option value="active">Active only</option><option value="archived">Archived only</option><option value="all">All records</option></select></label><button>Apply filters</button></form>
    <p><Link className={styles.export} href={`/admin/contacts/export?${new URLSearchParams(Object.entries(filterValues).filter(([, value]) => value && value !== "active") as [string, string][]).toString()}`}>Export CSV</Link></p>
    <p className={styles.summary}>{total} matching contact{total === 1 ? "" : "s"}.</p>{error ? <p className={styles.error} role="alert">Contacts could not be loaded.</p> : contacts.length === 0 ? <p className={styles.notice}>No contacts match these filters.</p> : <div className={styles.tableWrap}><table><thead><tr><th>Record ID</th><th>Name</th><th>Email</th><th>Organization</th><th>Country</th><th>Roles</th><th>Status</th><th>Created</th></tr></thead><tbody>{contacts.map((contact) => <tr key={contact.id}><td data-label="Record ID"><Link href={`/admin/contacts/${contact.id}`}>{contact.record_id}</Link>{contact.duplicate_status === "possible_duplicate" && <><span className={`${styles.badge} ${styles.duplicate}`}>Possible duplicate</span><br /><Link href={`/admin/duplicates/${contact.id}`}>Review matches</Link></>}</td><td data-label="Name">{contact.first_name} {contact.last_name}{contact.preferred_name ? <><br /><small>Preferred: {contact.preferred_name}</small></> : null}</td><td data-label="Email">{contact.email}</td><td data-label="Organization">{contact.organization ?? "—"}</td><td data-label="Country">{contact.country_region}</td><td data-label="Roles">{contact.roles.join(", ")}</td><td data-label="Status"><span className={styles.badge}>{contact.status.replaceAll("_", " ")}</span></td><td data-label="Created">{formatDate(contact.created_at)}</td></tr>)}</tbody></table></div>}
    <nav className={styles.pagination} aria-label="Pagination">{filters.page > 1 && <Link href={href(filterValues, filters.page - 1)}>Previous</Link>}<span>Page {filters.page} of {pages}</span>{filters.page < pages && <Link href={href(filterValues, filters.page + 1)}>Next</Link>}</nav></main>;
}
