import Link from "next/link";
import { notFound } from "next/navigation";
import { DeleteProspectButton } from "@/components/admin/delete-prospect-button";
import { ProspectSaveRedirect } from "@/components/admin/prospect-save-redirect";
import { requireApprovedAdmin } from "@/lib/auth/admin";
import { findPossibleDuplicates, getProspect } from "@/lib/prospects/admin-data";
import { prospectFlagOptions, sourceSupports, sourceTypes } from "@/lib/prospects/options";
import { safeProspectReturnTo } from "@/lib/prospects/save-flow";
import { addFlag, addSource, addTag, deleteFlag, deleteProspect, deleteSource, deleteTag, updateProspect, updateSource } from "../actions";
import { ProspectForm } from "../prospect-form";
import styles from "../../admin.module.css";
function date(value: string | null) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }

export default async function ProspectDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ saved?: string; error?: string; returnTo?: string }> }) {
  await requireApprovedAdmin(); const { id } = await params; const { prospect, sources, tags, flags } = await getProspect(id); if (!prospect) notFound(); const duplicates = await findPossibleDuplicates(id, prospect.public_email, prospect.first_name, prospect.last_name, prospect.organization); const query = await searchParams;
  return <main className={styles.page}>
    <header className={styles.header}><div><Link href="/admin/prospects">← Research Prospects</Link><h1>{prospect.first_name} {prospect.last_name}</h1><p>Externally researched prospect — not a self-submitted Contact and not communication consent.</p></div><form action="/admin/logout" method="post"><button>Sign out</button></form></header>
    {query.saved === "prospect" ? <ProspectSaveRedirect returnTo={safeProspectReturnTo(query.returnTo)} /> : query.saved ? <p className={styles.notice}>Research Prospect saved.</p> : null}{query.error && <p className={styles.error}>The requested change could not be saved.</p>}
    <section className={styles.detail}>
      <div className={styles.meta}><div><dt>Discovered</dt><dd>{date(prospect.discovered_at)}</dd></div><div><dt>Created</dt><dd>{date(prospect.created_at)}</dd></div><div><dt>Updated</dt><dd>{date(prospect.updated_at)}</dd></div><div><dt>Last verified</dt><dd>{date(prospect.last_verified_at)}</dd></div></div>
      <ProspectForm prospect={prospect} action={updateProspect.bind(null, id)} returnTo={safeProspectReturnTo(query.returnTo)}/>
      <section className={styles.compareCard}><h2>Sources</h2>{sources.map((source) => <form key={source.id} action={updateSource.bind(null, id, source.id)} className={styles.form}><label>Source URL<input name="sourceUrl" type="url" defaultValue={source.source_url} required/></label><label>Source type<select name="sourceType" defaultValue={source.source_type}>{sourceTypes.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></label><label>Source title<input name="sourceTitle" defaultValue={source.source_title ?? ""}/></label><label>Accessed at<input name="accessedAt" type="datetime-local" defaultValue={source.accessed_at?.slice(0, 16) ?? ""}/></label><fieldset><legend>Supports</legend><div className={styles.choices}>{sourceSupports.map((support) => <label key={support}><input type="checkbox" name="supports" value={support} defaultChecked={source.supports.includes(support)}/>{support.replaceAll("_", " ")}</label>)}</div></fieldset><div className={styles.mutations}><button>Save source</button><button formAction={deleteSource.bind(null, id, source.id)}>Remove source</button></div></form>)}<form action={addSource.bind(null, id)} className={styles.form}><label>Source URL<input name="sourceUrl" type="url" required/></label><label>Source type<select name="sourceType" defaultValue="official_profile">{sourceTypes.map((type) => <option key={type} value={type}>{type.replaceAll("_", " ")}</option>)}</select></label><label>Source title<input name="sourceTitle" maxLength={500}/></label><label>Accessed at<input name="accessedAt" type="datetime-local"/></label><fieldset><legend>Supports</legend><div className={styles.choices}>{sourceSupports.map((support) => <label key={support}><input type="checkbox" name="supports" value={support}/>{support.replaceAll("_", " ")}</label>)}</div></fieldset><div className={styles.mutations}><button>Add source</button></div></form></section>
      <section className={styles.compareCard}><h2>Research tags</h2><div className={styles.mutations}>{tags.length ? tags.map((entry) => { const tag = Array.isArray(entry.research_tags) ? entry.research_tags[0] : entry.research_tags; return <form key={entry.research_tag_id} action={deleteTag.bind(null, id, entry.research_tag_id)}><span className={styles.badge}>{tag?.name} <button aria-label={`Remove ${tag?.name}`}>×</button></span></form>; }) : <p>No tags recorded.</p>}</div><form action={addTag.bind(null, id)} className={styles.mutations}><input name="tag" placeholder="Add a reusable tag" maxLength={100} required/><button>Add tag</button></form></section>
      <section className={styles.compareCard}><h2>Verification flags</h2><div className={styles.mutations}>{flags.length ? flags.map((flag) => <form key={flag.id} action={deleteFlag.bind(null, id, flag.id)}><span className={`${styles.badge} ${styles.duplicate}`}>{flag.flag.replaceAll("_", " ")} <button aria-label={`Remove ${flag.flag}`}>×</button></span></form>) : <p>No flags recorded.</p>}</div><form action={addFlag.bind(null, id)} className={styles.mutations}><select name="flag">{prospectFlagOptions.map((flag) => <option key={flag} value={flag}>{flag.replaceAll("_", " ")}</option>)}</select><button>Add flag</button></form></section>
      {duplicates.length > 0 && <section className={styles.compareCard}><h2>Possible duplicates</h2><p>Matches by normalized public email, or where no email exists, by first name + last name + organization. Records are never merged automatically.</p><ul>{duplicates.map((match) => <li key={match.id}><Link href={`/admin/prospects/${match.id}`}>{match.first_name} {match.last_name}</Link> — {match.organization ?? "—"} ({match.public_email ?? "no email"})</li>)}</ul></section>}
      <form action={deleteProspect.bind(null, id)} className={`${styles.mutations} ${styles.danger}`}><DeleteProspectButton/></form>
    </section>
  </main>;
}
