"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireApprovedAdmin } from "@/lib/auth/admin";
import { createClient } from "@/lib/supabase/server";
import { validateProspect } from "@/lib/prospects/admin";
import { parseProspectCsv } from "@/lib/prospects/csv";
import { prospectSaveFailurePath, prospectSaveSuccessPath } from "@/lib/prospects/save-flow";
import { prospectFlagOptions, sourceSupports, sourceTypes } from "@/lib/prospects/options";
function refresh(id?: string) { revalidatePath("/admin/prospects"); if (id) revalidatePath(`/admin/prospects/${id}`); }
function formReturnTo(form: FormData) { const value = form.get("returnTo"); return typeof value === "string" ? value : null; }
export async function createProspect(form: FormData) { await requireApprovedAdmin(); const returnTo = formReturnTo(form); const validation = validateProspect(form); if (!validation.success) redirect(prospectSaveFailurePath("new", returnTo).replace("error=save", "error=invalid")); const supabase = await createClient(); const { data, error } = await supabase.from("research_prospects").insert(validation.data).select("id").single(); if (error || !data) redirect(prospectSaveFailurePath("new", returnTo)); refresh(data.id); redirect(prospectSaveSuccessPath(data.id, returnTo)); }
export async function updateProspect(id: string, form: FormData) { await requireApprovedAdmin(); const returnTo = formReturnTo(form); const validation = validateProspect(form); if (!validation.success) redirect(prospectSaveFailurePath(id, returnTo).replace("error=save", "error=invalid")); const { error } = await (await createClient()).from("research_prospects").update(validation.data).eq("id", id); if (error) redirect(prospectSaveFailurePath(id, returnTo)); refresh(id); redirect(prospectSaveSuccessPath(id, returnTo)); }
export async function deleteProspect(id: string) { await requireApprovedAdmin(); const { error } = await (await createClient()).from("research_prospects").delete().eq("id", id); if (error) redirect(`/admin/prospects/${id}?error=delete`); refresh(); redirect("/admin/prospects?deleted=1"); }
export async function addSource(id: string, form: FormData) { await requireApprovedAdmin(); const source_url = String(form.get("sourceUrl") ?? "").trim(); const source_type = String(form.get("sourceType") ?? ""); const supports = form.getAll("supports").filter((value): value is string => typeof value === "string" && sourceSupports.includes(value as typeof sourceSupports[number])); if (!/^https?:\/\//u.test(source_url) || !sourceTypes.includes(source_type as typeof sourceTypes[number]) || !supports.length) redirect(`/admin/prospects/${id}?error=source`); const { error } = await (await createClient()).from("research_prospect_sources").insert({ research_prospect_id: id, source_url, source_type, source_title: String(form.get("sourceTitle") ?? "").trim() || null, supports, accessed_at: String(form.get("accessedAt") ?? "").trim() || null }); if (error) redirect(`/admin/prospects/${id}?error=source`); refresh(id); redirect(`/admin/prospects/${id}?saved=1`); }
export async function deleteSource(id: string, sourceId: string) { await requireApprovedAdmin(); await (await createClient()).from("research_prospect_sources").delete().eq("id", sourceId).eq("research_prospect_id", id); refresh(id); redirect(`/admin/prospects/${id}?saved=1`); }
export async function updateSource(id: string, sourceId: string, form: FormData) { await requireApprovedAdmin(); const source_url = String(form.get("sourceUrl") ?? "").trim(); const source_type = String(form.get("sourceType") ?? ""); const supports = form.getAll("supports").filter((value): value is string => typeof value === "string" && sourceSupports.includes(value as typeof sourceSupports[number])); if (!/^https?:\/\//u.test(source_url) || !sourceTypes.includes(source_type as typeof sourceTypes[number]) || !supports.length) redirect(`/admin/prospects/${id}?error=source`); const { error } = await (await createClient()).from("research_prospect_sources").update({ source_url, source_type, source_title: String(form.get("sourceTitle") ?? "").trim() || null, supports, accessed_at: String(form.get("accessedAt") ?? "").trim() || null }).eq("id", sourceId).eq("research_prospect_id", id); if (error) redirect(`/admin/prospects/${id}?error=source`); refresh(id); redirect(`/admin/prospects/${id}?saved=1`); }
export async function addTag(id: string, form: FormData) { await requireApprovedAdmin(); const name = String(form.get("tag") ?? "").trim(); if (!name || name.length > 100) redirect(`/admin/prospects/${id}?error=tag`); const supabase = await createClient(); const { data: tag, error: tagError } = await supabase.from("research_tags").upsert({ name }, { onConflict: "normalized_name" }).select("id").single(); if (tagError || !tag) redirect(`/admin/prospects/${id}?error=tag`); const { error } = await supabase.from("research_prospect_tag_assignments").upsert({ research_prospect_id: id, research_tag_id: tag.id }); if (error) redirect(`/admin/prospects/${id}?error=tag`); refresh(id); redirect(`/admin/prospects/${id}?saved=1`); }
export async function deleteTag(id: string, tagId: string) { await requireApprovedAdmin(); await (await createClient()).from("research_prospect_tag_assignments").delete().eq("research_prospect_id", id).eq("research_tag_id", tagId); refresh(id); redirect(`/admin/prospects/${id}?saved=1`); }
export async function addFlag(id: string, form: FormData) { await requireApprovedAdmin(); const flag = String(form.get("flag") ?? ""); if (!prospectFlagOptions.includes(flag as typeof prospectFlagOptions[number])) redirect(`/admin/prospects/${id}?error=flag`); const { error } = await (await createClient()).from("research_prospect_flags").upsert({ research_prospect_id: id, flag }, { onConflict: "research_prospect_id,flag" }); if (error) redirect(`/admin/prospects/${id}?error=flag`); refresh(id); redirect(`/admin/prospects/${id}?saved=1`); }
export async function deleteFlag(id: string, flagId: string) { await requireApprovedAdmin(); await (await createClient()).from("research_prospect_flags").delete().eq("id", flagId).eq("research_prospect_id", id); refresh(id); redirect(`/admin/prospects/${id}?saved=1`); }
export async function importProspects(form: FormData) { await requireApprovedAdmin(); const file = form.get("file"); if (!(file instanceof File) || !file.size || file.size > 1024 * 1024) redirect("/admin/prospects/import?error=file"); let rows; try { rows = parseProspectCsv(await file.text()); } catch { redirect("/admin/prospects/import?error=csv"); } const { error } = await (await createClient()).from("research_prospects").insert(rows); if (error) redirect("/admin/prospects/import?error=save"); refresh(); redirect(`/admin/prospects?imported=${rows.length}`); }
